name: SQL Syntax Check

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  sql_lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install PostgreSQL (only for MySQL compatibility mode)
        if: contains(env.MYSQL_COMPAT, 'true')
        run: sudo apt-get update && sudo apt-get install -y postgresql-client
      - name: Install MySQL
        if: contains(env.MYSQL_COMPAT, 'false')
        run: sudo apt-get update && sudo apt-get install -y mysql-client
      - name: Install sqlfluff (SQL linter)
        run: pip install sqlfluff
      - name: Set MySQL compatibility flag (optional)
        env:
          MYSQL_COMPAT: ${{ github.event.inputs.mysql_compat || 'false' }}  # Default to False
      - name: Set DIALECT based on MYSQL_COMPAT (optional)
        env:
          DIALECT: ${{ (eq env.MYSQL_COMPAT 'true') && 'postgresql' || 'mysql' }}  # Choose 'postgresql' or 'mysql'
      - name: Perform SQL syntax check with sqlfluff
        run: |
          sqlfluff lint --dialect ${{ env.DIALECT }} ./*.sql --config ~/.sqlfluff/config.yaml
          # Optionally, capture output for more detailed messages
          # sqlfluff lint --dialect ${{ env.DIALECT }} ./*.sql --config ~/.sqlfluff/config.yaml > sqlfluff-output.txt 2>&1
      - name: Fail workflow on SQL syntax errors
        run: |
          if [[ $? -ne 0 ]]; then
            echo "⚠️ Found SQL syntax errors!"
            exit 1  # Signal workflow failure
          else
            echo " No SQL syntax errors found!"
          fi
