name: SQL Syntax Check

on:
  pull_request:
    branches:
      - main

jobs:
  sql_lint:
    name: SQL Syntax Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install sql-lint
        run: npm install -g sql-lint

      - name: Run SQL linting
        run: |
          sql-lint --ext .sql path/to/sql/files || true
