name: SQL Syntax Check

on:
  pull_request:
    paths:
      - '**.sql'  # Only trigger on changes to .sql files in pull requests

jobs:
  sql_lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install PostgreSQL (only for MySQL compatibility mode)
        if: contains(env.MYSQL_COMPAT, 'true')
        run: sudo apt-get update && sudo apt-get install -y postgresql-client
      - name: Install MySQL
        if: contains(env.MYSQL_COMPAT, 'false')
        run: sudo apt-get update && sudo apt-get install -y mysql-client
      - name: Install sqlfluff (SQL linter)
        run: pip install sqlfluff
      - name: Set MySQL compatibility flag (optional)
        env:
          MYSQL_COMPAT: ${{ github.event.inputs.mysql_compat || 'false' }}  # Default to False
      - name: Set DIALECT based on MYSQL_COMPAT (optional)
        env:
          DIALECT: ${{ (eq env.MYSQL_COMPAT 'true') && 'postgresql' || 'mysql' }}  # Choose 'postgresql' or 'mysql'
      - name: Check for changes in SQL files
        run: |
          if [[ -n "$(git diff --name-only HEAD^ HEAD '**.sql')" ]]; then
            # Changes detected, proceed with linting
            echo "Detected changes in SQL files:"
            git diff --name-only HEAD^ HEAD '**.sql'
            # ... (rest of the SQL syntax check steps from previous response)
          else
            echo "No changes in SQL files detected."
          fi
      - name: Fail workflow on SQL syntax errors (existing logic from previous response)
        # ... (existing step from previous response)
