name: SQL Syntax Check

on:
  pull_request:
    branches:
      - main

jobs:
  sql_lint:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install sqlfluff
        run: pip install sqlfluff

      - name: Perform SQL syntax check with sqlfluff
        run: |
          sqlfluff lint ./*.sql --config ~/.sqlfluff/config.yaml  # Adapt path if needed

      - name: Report on SQL syntax issues
        run: |
          # Check if sqlfluff exit code indicates errors
          if %ERRORLEVEL% NEQ 0 (
            echo " Found SQL syntax errors!"
            # Optionally, display more detailed error messages if desired
          ) else (
            echo " No SQL syntax errors found!"
          )
