name: SQL Syntax Check

on:
  pull_request:
    branches:
      - main

jobs:
  sql_lint:
    name: SQL Syntax Check
    runs-on: ubuntu-latest
    env:
      NODE_VERSION: '20.x'
    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install sql-lint
        run: npm install -g sql-lint

      - name: Run SQL linting
        run: |
          sql-lint --ext .sql path/to/sql/files
