name: SQL Syntax Check

on:
  pull_request:
    branches:
      - main

jobs:
  syntax_check:
    name: SQL Syntax Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install SQLLint
        run: npm install -g sql-lint

      - name: Find SQL files
        run: |
          SQL_FILES=$(find . -type f -name '*.sql')
          echo "$SQL_FILES" > sql_files.txt

      - name: Run SQLLint
        run: |
          while IFS= read -r FILE; do
            sql-lint "$FILE"
          done < sql_files.txt
